name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - name: â¤µï¸ Checkout the repository
      uses: actions/checkout@v4.1.7
    - name: ğŸ— Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: ğŸ— Install requirement
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: ğŸ— Install pylint
      run: python3 -m pip install pylint
    - name: ğŸš€ Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
